# Generated by Django 4.1.7 on 2023-03-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('field_of_study', models.PositiveSmallIntegerField(choices=[(0, 'ریاضی'), (1, 'تجربی'), (2, 'انسانی'), (3, 'هنر'), (4, 'زبان')], null=True)),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='SelectProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='booklet_information.province')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booklet_information.province')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='SelectProvinceForMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booklet_information.major')),
                ('select_province', models.ManyToManyField(to='booklet_information.selectprovince')),
            ],
        ),
        migrations.CreateModel(
            name='SelectDefaultProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booklet_information.province')),
            ],
        ),
        migrations.CreateModel(
            name='SelectDefaultMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booklet_information.major')),
            ],
        ),
        migrations.CreateModel(
            name='BookletRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_code', models.IntegerField(default=0)),
                ('exam_based', models.BooleanField(choices=[(True, 'با آزمون'), (False, 'صرفا با سوابق تحصیلی')], default=True)),
                ('course', models.PositiveSmallIntegerField(choices=[(0, 'روزانه'), (1, 'نوبت دوم'), (2, 'پردیس خودگردان'), (3, 'شهریه پرداز'), (4, 'پیام نور'), (5, 'غیر انتفاعی'), (6, 'مجازی'), (7, 'خودگردان آزاد'), (8, 'آزاد تمام وقت'), (9, 'فرهنگیان'), (10, 'بومی')], default=0)),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'دختر'), (1, 'پسر'), (2, 'هردو')], default=0)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booklet_information.major')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booklet_information.university')),
            ],
            options={
                'verbose_name': 'BookletRow',
                'verbose_name_plural': 'BookletRows',
            },
        ),
    ]
