# Generated by Django 4.1.1 on 2023-03-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_is_state_choose_booklet_rows_and_more'),
        ('booklet_information', '0002_selectdefaultmajor_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('booklet_row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booklet_information.bookletrow')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student')),
            ],
            options={
                'verbose_name': 'major selection',
                'verbose_name_plural': 'majors selection',
                'unique_together': {('booklet_row', 'student')},
            },
        ),
    ]
