# Generated by Django 4.1.7 on 2023-05-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_is_state_choose_booklet_rows_and_more'),
        ('booklet_information', '0003_majorselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectdefaultmajor',
            options={'verbose_name': 'SelectDefaultMajor', 'verbose_name_plural': 'SelectDefaultMajors'},
        ),
        migrations.AlterModelOptions(
            name='selectdefaultprovince',
            options={'verbose_name': 'SelectDefaultProvince', 'verbose_name_plural': 'SelectDefaultProvinces'},
        ),
        migrations.AlterModelOptions(
            name='selectprovince',
            options={'verbose_name': 'SelectProvince', 'verbose_name_plural': 'SelectProvinces'},
        ),
        migrations.AlterModelOptions(
            name='selectprovinceformajor',
            options={'verbose_name': 'SelectProvinceForMajor', 'verbose_name_plural': 'SelectProvinceForMajors'},
        ),
        migrations.AlterField(
            model_name='selectprovinceformajor',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booklet_information.major'),
        ),
        migrations.AlterUniqueTogether(
            name='majorselection',
            unique_together={('booklet_row', 'student')},
        ),
    ]
