# Generated by Django 4.1.1 on 2023-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet_information', '0004_alter_selectprovince_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectprovinceformajor',
            name='select_province',
            field=models.ManyToManyField(to='booklet_information.selectprovince'),
        ),
    ]
