# Generated by Django 4.1.1 on 2023-05-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklet_information', '0005_alter_selectprovinceformajor_select_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectprovince',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booklet_information.province'),
        ),
        migrations.AlterField(
            model_name='selectprovinceformajor',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booklet_information.major'),
        ),
    ]
