# Generated by Django 4.1.1 on 2023-08-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet_information', '0006_alter_selectprovince_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookletrow',
            name='admission',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ورودی مهر'), (1, 'ورودی بهمن')], default=0),
        ),
    ]
