# Generated by Django 4.1.1 on 2023-08-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet_information', '0007_bookletrow_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookletrow',
            name='admission',
            field=models.PositiveSmallIntegerField(choices=[(0, 'اول'), (1, 'دوم')], default=0),
        ),
        migrations.AlterField(
            model_name='major',
            name='field_of_study',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ریاضی'), (1, 'تجربی'), (2, 'انسانی'), (3, 'هنر'), (4, 'زبان'), (5, 'ریاضی 1'), (6, 'ریاضی و فیزیک')], null=True),
        ),
    ]
