# Generated by Django 4.2.9 on 2024-01-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booklet_information", "0009_alter_major_field_of_study"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="majorselection", unique_together=set(),),
        migrations.AddField(
            model_name="majorselection",
            name="head",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="MajorSelectionNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "major_selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="major_selection",
                        to="booklet_information.majorselection",
                    ),
                ),
                (
                    "next_major_selection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_major_selection",
                        to="booklet_information.majorselection",
                    ),
                ),
            ],
            options={
                "verbose_name": "major selection node",
                "verbose_name_plural": "majors selection node",
            },
        ),
        migrations.RemoveField(model_name="majorselection", name="rank",),
    ]
