# Generated by Django 4.2.9 on 2024-01-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_student_field_of_study"),
        ("booklet_information", "0010_alter_majorselection_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="majorselection",
            name="rank",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="majorselection", unique_together={("booklet_row", "student")},
        ),
        migrations.DeleteModel(name="MajorSelectionNode",),
        migrations.RemoveField(model_name="majorselection", name="head",),
    ]
