# Generated by Django 4.2.9 on 2024-02-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booklet_information", "0011_majorselection_rank_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="selectdefaultmajor",
            options={
                "verbose_name": "SelectDefaultMajor",
                "verbose_name_plural": "SelectDefaultMajors",
            },
        ),
        migrations.AlterModelOptions(
            name="selectdefaultprovince",
            options={
                "verbose_name": "SelectDefaultProvince",
                "verbose_name_plural": "SelectDefaultProvinces",
            },
        ),
        migrations.AlterModelOptions(
            name="selectprovince",
            options={
                "verbose_name": "SelectProvince",
                "verbose_name_plural": "SelectProvinces",
            },
        ),
        migrations.AlterModelOptions(
            name="selectprovinceformajor",
            options={
                "verbose_name": "SelectProvinceForMajor",
                "verbose_name_plural": "SelectProvinceForMajors",
            },
        ),
        migrations.AlterUniqueTogether(name="majorselection", unique_together=set(),),
        migrations.RemoveField(model_name="bookletrow", name="admission",),
        migrations.AddField(
            model_name="majorselection",
            name="head",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="major",
            name="field_of_study",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "ریاضی"),
                    (1, "تجربی"),
                    (2, "انسانی"),
                    (3, "هنر"),
                    (4, "زبان"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="selectprovince",
            name="province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="booklet_information.province",
            ),
        ),
        migrations.CreateModel(
            name="MajorSelectionNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "major_selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="major_selection",
                        to="booklet_information.majorselection",
                    ),
                ),
                (
                    "next_major_selection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_major_selection",
                        to="booklet_information.majorselection",
                    ),
                ),
            ],
            options={
                "verbose_name": "major selection node",
                "verbose_name_plural": "majors selection node",
            },
        ),
        migrations.RemoveField(model_name="majorselection", name="rank",),
    ]
