# Generated by Django 4.2.9 on 2024-03-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_student_field_of_study"),
        ("booklet_information", "0012_alter_selectdefaultmajor_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="selectdefaultmajor", options={},),
        migrations.AlterModelOptions(name="selectdefaultprovince", options={},),
        migrations.AlterModelOptions(
            name="selectprovince", options={"ordering": ("index",)},
        ),
        migrations.AlterModelOptions(name="selectprovinceformajor", options={},),
        migrations.AddField(
            model_name="bookletrow",
            name="admission",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "اول"), (1, "دوم")], default=0
            ),
        ),
        migrations.AddField(
            model_name="majorselection",
            name="rank",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="major",
            name="field_of_study",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "ریاضی"),
                    (1, "تجربی"),
                    (2, "انسانی"),
                    (3, "هنر"),
                    (4, "زبان"),
                    (5, "ریاضی 1"),
                    (6, "ریاضی و فیزیک"),
                    (7, "ریاضی جدید"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="selectprovince",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="booklet_information.province",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="majorselection", unique_together={("booklet_row", "student")},
        ),
        migrations.DeleteModel(name="MajorSelectionNode",),
        migrations.RemoveField(model_name="majorselection", name="head",),
    ]
