# Generated by Django 5.0.2 on 2024-07-25 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet_information', '0013_alter_selectdefaultmajor_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='majorselection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='majorselection',
            name='head',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MajorSelectionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_selection', to='booklet_information.majorselection')),
                ('next_major_selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_major_selection', to='booklet_information.majorselection')),
            ],
            options={
                'verbose_name': 'major selection node',
                'verbose_name_plural': 'majors selection node',
            },
        ),
        migrations.RemoveField(
            model_name='majorselection',
            name='rank',
        ),
    ]
