# Generated by Django 5.0.2 on 2024-07-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet_information', '0014_alter_majorselection_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorselection',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
