# Generated by Django 5.0.2 on 2024-09-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet_information', '0015_majorselection_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookletrow',
            name='boursie_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='bookletrow',
            name='course',
            field=models.PositiveSmallIntegerField(choices=[(0, 'روزانه'), (1, 'نوبت دوم'), (2, 'پردیس خودگردان'), (3, 'شهریه پرداز'), (4, 'پیام نور'), (5, 'غیر انتفاعی'), (6, 'مجازی'), (7, 'خودگردان آزاد'), (8, 'آزاد تمام وقت'), (9, 'فرهنگیان'), (10, 'بومی'), (11, 'بورسیه')], default=0),
        ),
    ]
