# Generated by Django 5.0.2 on 2024-09-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet_information', '0016_bookletrow_boursie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='rank_ensani',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='rank_riazi',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='rank_tajrobi',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
