# Generated by Django 5.0.2 on 2025-08-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet_information', '0017_university_rank_ensani_university_rank_riazi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookletrow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookletrow',
            name='course',
            field=models.PositiveSmallIntegerField(choices=[(0, 'روزانه'), (1, 'نوبت دوم'), (2, 'پردیس خودگردان'), (3, 'شهریه پرداز'), (4, 'پیام نور'), (5, 'غیر انتفاعی'), (6, 'مجازی'), (7, 'خودگردان آزاد'), (8, 'آزاد تمام وقت'), (9, 'فرهنگیان'), (10, 'بومی'), (11, 'بورسیه'), (12, 'بهیاری')], default=0),
        ),
    ]
