# Generated by Django 4.1.7 on 2023-03-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='report_card_file',
            field=models.FileField(blank=True, null=True, upload_to='report_card_file'),
        ),
    ]
