# Generated by Django 4.1.1 on 2023-05-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_is_state_choose_booklet_rows_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_state_choose_booklet_rows',
        ),
        migrations.AddField(
            model_name='student',
            name='is_state_final_approval',
            field=models.BooleanField(default=False),
        ),
    ]
