# Generated by Django 4.1.1 on 2023-08-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_student_is_state_choose_booklet_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='otp_key'),
        ),
    ]
