# Generated by Django 5.0.2 on 2024-07-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_field_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='process_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='process_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
