# Generated by Django 5.0.2 on 2024-08-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_student_f_count_student_f_percentage_student_i_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='e_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='e_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
